### ISSUE TITLE
Package didn't upload

### ISSUE THREAD

**Issue by hadim** [conda-forge/scyjava-feedstock#1]
@scopatz It looks like Travis didn't upload the package while the build is green: https://travis-ci.com/conda-forge/scyjava-feedstock/builds/92027726#L706

Do you know what could have happened?

Also, I don't see the build for py3.7, is it automatic or do I have to make something to enable py3.7?

Thank you for your time again!

**Comment by hanslovsky** [comment]
@hadim the builds on [circle-ci](https://circleci.com/gh/conda-forge/scyjava-feedstock/1?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) and [appveyor](https://ci.appveyor.com/project/conda-forge/scyjava-feedstock/builds/20435104) are still pending. You will probably have to weight until those are completed.

Update: Nevermind, that might not be the case, actually.

**Comment by hadim** [comment]
I think packages are uploaded independently from other builds (but I might be wrong...).

**Comment by hadim** [comment]
Windows build has been uploaded. I'll try to restart the Travis one.

**Comment by hadim** [comment]
Restarting it, didn't work.

**Comment by hadim** [comment]
I'm confused because the package did get uploaded on Anaconda but I have no idea where that happened.

Anyway, it's fixed :-D
